server:
  port: 8888

spring:
  application:
    name: oauth-service
  # mysql数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/jap_ids_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: my-llh0901-sql
  # redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms  # 连接超时时长（毫秒）
  # thymeleaf
  thymeleaf:
    cache: false

# mybatis配置
mybatis:
  type-aliases-package: com.fujieid.oauth.entity
  mapper-locations: classpath:mapper/**/*.xml
# LOG
logging:
  level:
    root: info
# oauth2.0服务配置
#ids:
#  oauth2:
#    enable-redis-cache: true

