server:
  port: 8888

spring:
  application:
    name: oauth-service
  # mysql数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/jap_ids_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: my-llh0901-sql
  # redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  # thymeleaf
  thymeleaf:
    cache: false

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# LOG
logging:
  level:
    root: info
# oauth2.0服务配置
japids:
  config:
    enable-external-confirm: true
    enable-external-login: true
    extra-scope: { dog: 'dog', cat: 'cat' }

